-- MySQL Script generated by MySQL Workbench
-- jue 12 ene 2023 19:02:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Players` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Players` (
  `idPlayer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT 'noData',
  `age` INT NULL DEFAULT 0,
  `position1` VARCHAR(45) NULL DEFAULT 'noData',
  `position2` VARCHAR(45) NULL DEFAULT 'noData',
  `position3` VARCHAR(45) NULL DEFAULT 'noData',
  `collegue` VARCHAR(45) NULL DEFAULT 'noData',
  `draftTeam` VARCHAR(45) NULL DEFAULT 'noData',
  `draftPosition` INT NULL DEFAULT 0,
  `draftYear` YEAR(4) NULL DEFAULT 0000,
  `born` DATE NULL,
  `experience` INT NULL DEFAULT 0,
  PRIMARY KEY (`idPlayer`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Games` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Games` (
  `idGame` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `visitor` VARCHAR(45) NULL,
  `local` VARCHAR(45) NULL,
  `pointsVisitor` INT NULL,
  `pointsLocal` INT NULL,
  `arena` VARCHAR(45) NULL,
  PRIMARY KEY (`idGame`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Seasons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Seasons` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Seasons` (
  `idSeason` INT NOT NULL AUTO_INCREMENT,
  `years` VARCHAR(45) NULL,
  `league` VARCHAR(45) NULL,
  `champion` INT NULL COMMENT 'idTeam',
  `mvp` INT NULL COMMENT 'idPlayer',
  `roty` INT NULL COMMENT 'idPlayer',
  `pointsLeader` INT NULL COMMENT 'idPlayer',
  `reboundsLeader` INT NULL COMMENT 'idPlayer',
  `assistsLeader` INT NULL COMMENT 'idPlayer',
  `winShareLeader` INT NULL COMMENT 'idPlayer',
  `pointsMax` INT NULL,
  `reboundsMax` INT NULL,
  `assistsMax` INT NULL,
  `winSharesMax` INT NULL,
  PRIMARY KEY (`idSeason`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Teams` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Teams` (
  `idTeam` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `games` VARCHAR(45) NULL,
  `wins` VARCHAR(45) NULL,
  `loses` VARCHAR(45) NULL,
  `playoff` VARCHAR(45) NULL,
  `confChampions` VARCHAR(45) NULL,
  `nbaChampions` VARCHAR(45) NULL,
  `conference` VARCHAR(45) NULL,
  PRIMARY KEY (`idTeam`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`PlayerPerGame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PlayerPerGame` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`PlayerPerGame` (
  `idPlayer` INT NOT NULL,
  `idGame` INT NOT NULL,
  `idTeam` INT NOT NULL,
  `minutesPlayed` DATETIME NULL,
  `fieldGoals` INT NULL DEFAULT 0,
  `fgAttempts` INT NULL DEFAULT 0,
  `fgPerc` FLOAT NULL DEFAULT 0.0,
  `3PtsFG` INT NULL DEFAULT 0,
  `3PFGAttempts` INT NULL DEFAULT 0,
  `3PFGPerc` FLOAT NULL DEFAULT 0.0,
  `freeThrows` INT NULL DEFAULT 0,
  `freeThorwsAttemps` INT NULL,
  `FTPerc` FLOAT NULL DEFAULT 0.0,
  `offRbds` INT NULL DEFAULT 0,
  `defRbds` INT NULL DEFAULT 0,
  `totalRbds` INT NULL DEFAULT 0,
  `assists` INT NULL DEFAULT 0,
  `steals` INT NULL DEFAULT 0,
  `blocks` INT NULL DEFAULT 0,
  `turnovers` INT NULL DEFAULT 0,
  `fouls` INT NULL DEFAULT 0,
  `points` INT NULL DEFAULT 0,
  `punctuation` INT NULL DEFAULT 0,
  PRIMARY KEY (`idPlayer`, `idGame`),
  CONSTRAINT `fk_PlayerPerGame_Players`
    FOREIGN KEY (`idPlayer`)
    REFERENCES `mydb`.`Players` (`idPlayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlayerPerGame_Games1`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Games` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlayerPerGame_Teams1`
    FOREIGN KEY (`idTeam`)
    REFERENCES `mydb`.`Teams` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_PlayerPerGame_Games1_idx` ON `mydb`.`PlayerPerGame` (`idGame` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_PlayerPerGame_Teams1_idx` ON `mydb`.`PlayerPerGame` (`idTeam` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`PlayerSeasons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PlayerSeasons` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`PlayerSeasons` (
  `idPlayer` INT NOT NULL,
  `idSeason` INT NOT NULL,
  `idTeam` INT NULL,
  `age` INT NULL,
  `league` VARCHAR(45) NULL,
  `position` VARCHAR(45) NULL,
  `games` INT NULL,
  `gamesStarter` INT NULL,
  `minutesPlayed` INT NULL,
  `fieldGoals` INT NULL,
  `FGAttempts` INT NULL,
  `FGPerc` FLOAT NULL,
  `3PtsFG` INT NULL,
  `3PFGAttempts` INT NULL,
  `3PFGPerc` FLOAT NULL,
  `2PtsFG` INT NULL,
  `2PFGAttempts` INT NULL,
  `2PFGPerc` FLOAT NULL,
  `effectiveGoalPerc` FLOAT NULL,
  `freeThrows` INT NULL,
  `freeThorwsAttemps` INT NULL,
  `FTPerc` FLOAT NULL,
  `offRbds` INT NULL,
  `defRbds` INT NULL,
  `totalRbds` INT NULL,
  `assists` INT NULL,
  `steals` INT NULL,
  `blocks` INT NULL,
  `turnovers` INT NULL,
  `fouls` INT NULL,
  `points` INT NULL,
  `tripleDouble` INT NULL,
  PRIMARY KEY (`idPlayer`, `idSeason`),
  CONSTRAINT `fk_PlayerSeasons_Players1`
    FOREIGN KEY (`idPlayer`)
    REFERENCES `mydb`.`Players` (`idPlayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlayerSeasons_Seasons1`
    FOREIGN KEY (`idSeason`)
    REFERENCES `mydb`.`Seasons` (`idSeason`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlayerSeasons_Teams1`
    FOREIGN KEY (`idTeam`)
    REFERENCES `mydb`.`Teams` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_PlayerSeasons_Seasons1_idx` ON `mydb`.`PlayerSeasons` (`idSeason` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_PlayerSeasons_Teams1_idx` ON `mydb`.`PlayerSeasons` (`idTeam` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TeamPerSeason`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TeamPerSeason` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`TeamPerSeason` (
  `idSeason` INT NOT NULL,
  `idTeam` INT NOT NULL,
  `position` INT NULL DEFAULT 0,
  `wins` INT NULL DEFAULT 0,
  `loses` INT NULL DEFAULT 0,
  `winRate` FLOAT NULL DEFAULT 0.0,
  `gamesBehind` FLOAT NULL DEFAULT 0.0,
  `ptsGame` FLOAT NULL DEFAULT 0.0,
  `defPTSGame` FLOAT NULL DEFAULT 0.0,
  `teamRating` FLOAT NULL DEFAULT 0.0,
  `conference` VARCHAR(15) NULL DEFAULT 'noData',
  PRIMARY KEY (`idSeason`, `idTeam`),
  CONSTRAINT `fk_TeamPerSeason_Seasons1`
    FOREIGN KEY (`idSeason`)
    REFERENCES `mydb`.`Seasons` (`idSeason`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TeamPerSeason_Teams1`
    FOREIGN KEY (`idTeam`)
    REFERENCES `mydb`.`Teams` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_TeamPerSeason_Teams1_idx` ON `mydb`.`TeamPerSeason` (`idTeam` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
